name: Build and deploy

on:
  push:
    branches:
      - disabled

env:
  NODE_ENV: production
  JEKYLL_ENV: production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: jekyll

      # Node
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1

      # Build
      - name: Build
        run: yarn build

      # Deploy
      - name: Deploy to Firebase
        run: ./node_modules/.bin/firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
