name: Build and deploy

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production
  JEKYLL_ENV: production

jobs:
  build_and_deploy:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: jekyll

      # Node
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install
      - name: Build
        run: yarn install

      # Build
      - name: Build
        run: yarn build

      # Deploy
      - name: Deploy to Firebase
        run: ./node_modules/.bin/firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
