name: Build and deploy

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production
  JEKYLL_ENV: production

jobs:
  build_and_deploy:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Deploy to Firebase
        run: ./node_modules/.bin/firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
